/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import API.ConectionDB;
import Objs.ObjsCompras;
import ModelTables.CompraTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Vitor.hvieira1
 */
public class TelaCompra extends javax.swing.JFrame {

    CompraTableModel model = new CompraTableModel();
    ObjsCompras obj = new ObjsCompras();
    ConectionDB CDB = new ConectionDB();

    /**
     * Creates new form Compra
     */
    public TelaCompra() {
        initComponents();
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkbox1 = new java.awt.Checkbox();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pedidos = new javax.swing.JButton();
        cnpj = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        forma_de_pagamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nota_fiscal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        numero_nota_fiscal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        codigo_med = new javax.swing.JTextField();
        quantidade = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        valor_unitario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        valor_total = new javax.swing.JTextField();
        data_de_entrega = new javax.swing.JFormattedTextField();
        data_compra = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        checkbox1.setLabel("checkbox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("compras");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 244, 862, 107));

        pedidos.setText("compra");
        pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosActionPerformed(evt);
            }
        });
        getContentPane().add(pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 186, -1, -1));

        cnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpjActionPerformed(evt);
            }
        });
        getContentPane().add(cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, 167, -1));

        jLabel1.setText("CNPJ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        jLabel2.setText("Forma de pagamento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 37, -1, -1));
        getContentPane().add(forma_de_pagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 34, 81, -1));

        jLabel3.setText("Data de entrega");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 65, -1, -1));

        jLabel4.setText("Data compra");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 93, -1, -1));

        jLabel5.setText("Nota fiscal");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 118, -1, -1));
        getContentPane().add(nota_fiscal, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 118, 130, -1));

        jLabel6.setText("Numero nota fiscal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 9, -1, -1));

        numero_nota_fiscal.setEditable(false);
        getContentPane().add(numero_nota_fiscal, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 6, 143, -1));

        jLabel7.setText("Codigo Medicamento");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 37, -1, -1));
        getContentPane().add(codigo_med, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 34, 157, -1));
        getContentPane().add(quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 62, 211, -1));

        jLabel8.setText("Quantidade");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 65, -1, -1));

        valor_unitario.setEditable(false);
        getContentPane().add(valor_unitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 90, 201, -1));

        jLabel9.setText("Valor Unitario");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 93, -1, -1));

        jLabel10.setText("Valor total");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 121, -1, -1));

        valor_total.setEditable(false);
        getContentPane().add(valor_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 118, 219, -1));

        try {
            data_de_entrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(data_de_entrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 62, 110, -1));

        try {
            data_compra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(data_compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 120, -1));

        jButton1.setText("Calcular valores");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, -1, -1));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosActionPerformed
        // TODO add your handling code here:

        obj.setCnpj_Lab(cnpj.getText());
        obj.setFormaPag_L(forma_de_pagamento.getText());
        obj.setDataEntega_L((data_de_entrega.getText()));
        obj.setCod_Med(codigo_med.getText());
        obj.setQntd_Med((int) quantidade.getValue());
        obj.setDataCompra_L(data_compra.getText());


        obj.setTotalNota_L(Double.valueOf(nota_fiscal.getText()));

        obj.setValorTotal(Double.valueOf(valor_total.getText()));
        valor_unitario.getText();

        boolean a;
        a = CDB.newCompra(obj.getCnpj_Lab(), obj.getFormaPag_L() ,obj.getDataEntega_L() , obj.getDataCompra_L(),  obj.getTotalNota_L().toString(), obj.getCod_Med(), obj.getQntd_Med(), obj.getValor_Unit(), obj.getValorTotal());
        if (a) {
            obj.setNumNotaFiscal_L(numero_nota_fiscal.getText());
            try {
            Connection c;
            c = java.sql.DriverManager.getConnection(CDB.conecte);
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery("SELECT *FROM Pedidos_Compra WHERE Cod_Med='" + cnpj.getText() + "'");
            while (rs.next()) {
                obj.setNumNotaFiscal_L(rs.getString("NumNotaFiscal_L"));
            }
            } catch (Exception e) {
        }finally{
                numero_nota_fiscal.setText(obj.getNumNotaFiscal_L());
            model.addLinha(obj);
            cnpj.requestFocus();
            }
        }


    }//GEN-LAST:event_pedidosActionPerformed

    private void cnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpjActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Connection c;
            c = java.sql.DriverManager.getConnection(CDB.conecte);
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery("SELECT *FROM medicamentos WHERE Cod_Med = '"+codigo_med.getText()+"';");
            while (rs.next()) {
                obj.setValor_Unit((rs.getDouble("Valor_Custo")));
            }
            obj.setValorTotal(obj.getQntd_Med()*obj.getValor_Unit());
            valor_total.setText(obj.getValorTotal().toString());
            valor_unitario.setText(obj.getValor_Unit().toString());
            }catch (Exception e) {
            System.out.println(e.getMessage());
        }finally{
            obj.setValorTotal(obj.getQntd_Med()*obj.getValor_Unit());
            valor_total.setText(obj.getValorTotal().toString());
            valor_unitario.setText(obj.getValor_Unit().toString());
        } 

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CDB.deletarCompras(numero_nota_fiscal.getText(), codigo_med.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObjsCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObjsCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObjsCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObjsCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkbox1;
    private javax.swing.JTextField cnpj;
    private javax.swing.JTextField codigo_med;
    private javax.swing.JFormattedTextField data_compra;
    private javax.swing.JFormattedTextField data_de_entrega;
    private javax.swing.JTextField forma_de_pagamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nota_fiscal;
    private javax.swing.JTextField numero_nota_fiscal;
    private javax.swing.JButton pedidos;
    private javax.swing.JSpinner quantidade;
    private javax.swing.JTextField valor_total;
    private javax.swing.JTextField valor_unitario;
    // End of variables declaration//GEN-END:variables
}
